[[materials]]
id = "al-2024(jc)"
name = { ru = "Алюминий AL2024", en = "Aluminium AL2024" }
reference = "https://example.com/hexolite"
comment = { ru = "Алюминий AL2024 (аналог отечественного Д16)", en = "Aluminium AL2024" }
tags = { ru = ["алюминий", "кумулятивная облицовка", "корпус"], en = ["aluminium", "shaped charge liner", "cases"] }

[materials.material]
model = "mat-jc"
units = "mm-mg-us"
payload = """*MAT_JOHNSON_COOK_TITLE
MAT_AL2024
$#     mid        ro         g         e        pr       dtf        vp    rateop
        42     2.785      27.6       0.0       0.0       0.0       0.0       0.0
$#       a         b         n         c         m        tm        tr      epso
     0.265     0.426      0.34     0.015       1.0     775.0     293.01.00000E-6
$#      cp        pc     spall        it        d1        d2        d3        d4
8.75000E-4       0.0       2.0       0.0       0.0       0.0       0.0       0.0
$#      d5c2/p/xnp/d      erod     efmin    numint         k      eps1
       0.0       0.0       0.01.00000E-6       0.0       0.0       0.0
"""

[materials.eos]
model = "eos-gruneisen"
units = "mm-mg-us"
payload = """*EOS_GRUNEISEN_TITLE
EOS_AL2024
$#   eosid         c        s1        s2        s3    gamma0         a        e0
        32     5.328     1.338       0.0       0.0       2.0       0.0       0.0
$#      v0    unused      lcid
       0.0                   0
"""

[[materials]]
id = "steel-aisi-1045(jc)"
name = { ru = "Сталь AISI-1045", en = "Steel AISI-1045" }
reference = "https://example.com/hexolite"
comment = { ru = "Сталь Сталь AISI-1045 (аналог стали 45)", en = "Steel AISI-1045" }
tags = { ru = ["медь", "корпус"], en = ["copper", "cases"] }

[materials.material]
model = "mat-jc"
units = "mm-mg-us"
payload = """*MAT_JOHNSON_COOK_TITLE
MAT_St_1045
$#     mid        ro         g         e        pr       dtf        vp    rateop
        46      7.85      78.0       0.0       0.0       0.0       0.0       0.0
$#       a         b         n         c         m        tm        tr      epso
     0.553       0.6     0.234     0.026       1.0    1733.0     293.01.00000E-6
$#      cp        pc     spall        it        d1        d2        d3        d4
4.52000E-4       0.0       2.0       0.0       0.0       0.0       0.0       0.0
$#      d5c2/p/xnp/d      erod     efmin    numint         k      eps1
       0.0       0.0       0.01.00000E-6       0.0       0.0       0.0
"""

[materials.eos]
model = "eos-gruneisen"
units = "mm-mg-us"
payload = """*EOS_GRUNEISEN_TITLE
EOS_St_1045
$#   eosid         c        s1        s2        s3    gamma0         a        e0
        36     4.569      1.49       0.0       0.0      2.17       0.0       0.0
$#      v0    unused      lcid
       0.0                   0
"""

[[materials]]
id = "steel(m10)"
name = { ru = "Сталь (MAT_010)", en = "Steel (MAT_010)" }
reference = "https://example.com/mat010"
comment = { ru = "Пример материала на модели MAT_ELASTIC_PLASTIC_HYDRO", en = "Example material using MAT_ELASTIC_PLASTIC_HYDRO" }
tags = { ru = ["сталь", "mat_010"], en = ["steel", "mat_010"] }

[materials.material]
model = "mat-elastic-plastic-hydro"
units = "mm-mg-us"
payload = """*MAT_ELASTIC_PLASTIC_HYDRO_TITLE
Steel-M10
$#     mid        ro         g      sig0        eh        pc        fs     charl
       301     7.850      80.0      0.25      0.15       0.0      0.30       2.0
$#     eps1      eps2      eps3      eps4      eps5      eps6      eps7      eps8
       0.0      0.01      0.02      0.03      0.04      0.05      0.06      0.07
$#     eps9     eps10     eps11     eps12     eps13     eps14     eps15     eps16
      0.08      0.09      0.10      0.11      0.12      0.13      0.14      0.15
$#      es1       es2       es3       es4       es5       es6       es7       es8
      0.25      0.30      0.35      0.40      0.45      0.50      0.55      0.60
$#      es9      es10      es11      es12      es13      es14      es15      es16
      0.65      0.70      0.75      0.80      0.85      0.90      0.95      1.00
"""
